### ISSUE TITLE
Connection: Esc = Cancel

### ISSUE THREAD

**Issue by rappen** [MscrmTools/XrmToolBox#1245]
A tiny thing, but Esc should close the window.

---
- Deployment: Online
- DB Version: 9.2.23022.178
- Connection Controls Version: 1.2023.2.55
- XrmToolBox Version: 1.2023.3.64

**Comment by MscrmTools** [comment]
Fixed. I will release a new version soon

**Comment by rappen** [comment]
Still doesn't work though...

Both Enter and Esc.

![image](https://user-images.githubusercontent.com/2572253/225339192-20f8b971-6589-4cbb-af3d-f126615435b4.png)

**Comment by MscrmTools** [comment]
from what I see, you are not using the appropriate version. Is it beta10? or 9?

**Comment by MscrmTools** [comment]
This issue comes with connection controls, not XrmToolBox itself. and XTB beta v2 does not embed this fix

**Comment by rappen** [comment]
Ah ofc, stupid me. Will check again.
