### ISSUE TITLE
Cannot Connect

### ISSUE THREAD

**Issue by RBellefond** [MscrmTools/XrmToolBox#363]
Hi.  I have CRM 2016 On Premise with 0.1 update with IFD.

I have version 1.2016.2.28 of XRMToolBox.

When I try to create a connection either from either a laptop that I can connect to CRM 2016 or from the server where my CRM 2016 resides once I I enter my credentials and try to connect I get a message saying:

New Connection
Your information have not been validated

Unable to login to Dynamics CRM.

Any idea as to what I need to do to be able to use XRMToolBox?

Thanks

Rick Bellefond
RB Data Services
www.rbdata.com

**Comment by MscrmTools** [comment]
Never tested this exact scenario...
Can you share the screenshot of the connection wizard?

**Comment by MscrmTools** [comment]
You can also [activate tracing](https://github.com/MscrmTools/XrmToolBox/wiki/Enable-tracing-in-XrmToolBox)

**Comment by Rsilla** [comment]
Hi. Having the same issue with CRM 2015 on premise....HELP!

**Comment by Rsilla** [comment]
still unable to login to dynaimcs crm____HELP!!!

**Comment by xairrick** [comment]
I can't ever get IFD to work with the new connection dialog.

**Comment by SLewis-Venteon** [comment]
Using version XRMToolBox v1.2016.3.30 -   I am not able to make a connection with CRM 2015 on premise.  Connected fine with my Dev environment that is not ADFS.  I have tried connection string also but still get the message "Unable to connect to Dynamics CRM"  Does anyone have a solution or similar problem?

**Comment by MscrmTools** [comment]
Does it mean the environment you are trying to connect is using ADFS?
The latest version lets you use a connection string that can connect to virtually any deployment

**Comment by Rsilla** [comment]
hi! i have this issue for the longest time.

Please where can i get info about using the connections string

**Comment by MscrmTools** [comment]
All links for help are in the connection wizard

**Comment by SLewis-Venteon** [comment]
I didn’t need to use connection sting, I ended up adding domain to the username and the domain field.  Example below

Domain: Pepsi
Username: pepsi\slewis     (add the domain and forward slash infront of username. )
Passowrd: passcode

[cid:image007.jpg@01D18F3B.A24BBCD0]Shane Lewis | Manager – IT Recruiting
Venteon Partners - Information Technology Practice
O: 248.633.2521 | Cell: 248.602.1064
[Staffing Specialists][cid:image010.png@01CEA4B7.A7690090]<http://www.linkedin.com/company/2166352>

**Comment by RBellefond** [comment]
SLewis-Venteon's suggestion of adding the domain\username as in the example:

Domain: Pepsi 
Username: pepsi\slewis (add the domain and forward slash infront of username. ) 
Passowrd: passcode 

fixed my connection issue that I have been having months.

Thank you!

Rick Bellefond
RB Data Services

**Comment by SLewis-Venteon** [comment]
That is great. I can imagine how frustrating. I was ready to pull my hair out myself....ha

Sent from my Verizon 4G LTE Droid
On Apr 9, 2016 4:59 AM, RBellefond <notifications@github.com> wrote:

SLewis-Venteon's suggestion of adding the domain\username as in the example:

Domain: Pepsi
Username: pepsi\slewis (add the domain and forward slash infront of username. )
Passowrd: passcode

fixed my connection issue that I have been having months.

Thank you!

Rick Bellefond
RB Data Services

**Comment by Rsilla** [comment]
still unable to connect with the connection string and adding the
domain\username approach. Soooo frustrated.

**Comment by SLewis-Venteon** [comment]
Did you do with connection wizard. I did not need to use the connection string

Sent from my Verizon 4G LTE Droid
On Apr 9, 2016 10:26 AM, Rsilla <notifications@github.com> wrote:
still unable to connect with the connection string and adding the
domain\username approach. Soooo frustrated.

**Comment by Rsilla** [comment]
Tried everything. No joy. Something to do with our front ends being on a
nlb clusters. And i soo badly need to use the fetchxml utility....😣😣

**Comment by MscrmTools** [comment]
Did you succeed to connect to your organization?
any trace on the logs?

**Comment by Rsilla** [comment]
Hi. Unfortunately no

**Comment by MscrmTools** [comment]
ok, can you [activate the trace](https://github.com/MscrmTools/XrmToolBox/wiki/Enable-tracing-in-XrmToolBox) and see what the logs say?

**Comment by AntonioRomera** [comment]
For me the problem wasn't solver by the "domain\user" method... 

I did activate trace and it showed that there's a problem with the "Plugin Registration" Plugin by Trou Macacq.

Removed plugin and started working (connecting) again :smile:

**Comment by xairrick** [comment]
WIth the latest version (1.2016.4.28)  I was finally able to connect to IFD using the following connection string;
ServiceUri=https://<HOSTNAME>:<PORTNUM>/<ORGNAME>;AuthType=IFD;Domain=<DOMAIN>;UserName=<DOMAIN>\<USERNAME>;Password=<PASSWORD>;LoginPrompt=Never;

NOTE: Even Though the hostname included the orgname, I still had to include the orgname on the uri.

**Comment by MscrmTools** [comment]
Great news, every one!

I close the issue

**Comment by DS-CRM** [comment]
I am also facing the same issue!!

I tried using xairrick response but still getting error.

**ID3242: The security token could not be authenticated or authorized.**

This is what I am getting.

**Comment by edwardbeckett** [comment]
@xairrick ~ You rock mate ... :)_

**Comment by sera0731** [comment]
When I add connection successfully and select the connection, I get the following error..

`이 대화 상자 대신 JIT(Just-in-time) 디버깅을 호출하는
방법에 대한 자세한 내용은 이 메시지의 뒷부분을 참조하십시오.

************** 예외 텍스트 **************
System.InvalidOperationException: The user authentication failed!
   위치: Microsoft.Xrm.Sdk.Client.ServiceProxy`1.AuthenticateCore()
   위치: Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CheckForConnectionTokenTimeOut()
   위치: Microsoft.Xrm.Tooling.Connector.CrmWebSvc.get_CrmSvc()
   위치: Microsoft.Xrm.Tooling.Connector.CrmServiceClient.get_OrganizationServiceProxy()
   위치: McTools.Xrm.Connection.ConnectionManager.WorkerRunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e)
   위치: System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)


************** 로드된 어셈블리 **************
mscorlib
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2633.0 built by: NET471REL1LAST_C
    코드베이스: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
XrmToolBox
    어셈블리 버전: 1.2018.7.28
    Win32 버전: 1.2018.7.28
    코드베이스: file:///D:/XrmToolbox/XrmToolBox.exe
----------------------------------------
System.Core
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2633.0 built by: NET471REL1LAST_C
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0 built by: NET471REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
XrmToolBox.Extensibility
    어셈블리 버전: 1.2018.7.28
    Win32 버전: 1.2018.7.28
    코드베이스: file:///D:/XrmToolbox/XrmToolBox.Extensibility.DLL
----------------------------------------
System.Windows.Forms
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0 built by: NET471REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0 built by: NET471REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.IdentityModel
    어셈블리 버전: 3.5.0.0
    Win32 버전: 6.1.7600.16394
    코드베이스: file:///D:/XrmToolbox/Microsoft.IdentityModel.DLL
----------------------------------------
System.IO.Compression.FileSystem
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------
XrmToolBox.PluginsStore
    어셈블리 버전: 1.2018.7.28
    Win32 버전: 1.2018.7.28
    코드베이스: file:///D:/XrmToolbox/XrmToolBox.PluginsStore.DLL
----------------------------------------
NuGet.Core
    어셈블리 버전: 2.14.0.832
    Win32 버전: 2.14.0.832
    코드베이스: file:///D:/XrmToolbox/NuGet.Core.DLL
----------------------------------------
Newtonsoft.Json
    어셈블리 버전: 11.0.0.0
    Win32 버전: 11.0.2.21924
    코드베이스: file:///D:/XrmToolbox/Newtonsoft.Json.DLL
----------------------------------------
McTools.Xrm.Connection
    어셈블리 버전: 1.2018.7.19
    Win32 버전: 1.2018.7.19
    코드베이스: file:///D:/XrmToolbox/McTools.Xrm.Connection.DLL
----------------------------------------
McTools.Xrm.Connection.WinForms
    어셈블리 버전: 1.2018.7.19
    Win32 버전: 1.2018.7.19
    코드베이스: file:///D:/XrmToolbox/McTools.Xrm.Connection.WinForms.DLL
----------------------------------------
Microsoft.Xrm.Sdk
    어셈블리 버전: 9.0.0.0
    Win32 버전: 9.0.0002.0165
    코드베이스: file:///D:/XrmToolbox/Microsoft.Xrm.Sdk.DLL
----------------------------------------
Microsoft.Xrm.Sdk.Workflow
    어셈블리 버전: 9.0.0.0
    Win32 버전: 9.0.0002.0165
    코드베이스: file:///D:/XrmToolbox/Microsoft.Xrm.Sdk.Workflow.DLL
----------------------------------------
Microsoft.Crm.Sdk.Proxy
    어셈블리 버전: 9.0.0.0
    Win32 버전: 9.0.0002.0165
    코드베이스: file:///D:/XrmToolbox/Microsoft.Crm.Sdk.Proxy.DLL
----------------------------------------
Microsoft.Xrm.Tooling.Connector
    어셈블리 버전: 3.0.0.0
    Win32 버전: 3.0.0.931
    코드베이스: file:///D:/XrmToolbox/Microsoft.Xrm.Tooling.Connector.DLL
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory
    어셈블리 버전: 2.29.0.1078
    Win32 버전: 2.29.40822.1520
    코드베이스: file:///D:/XrmToolbox/Microsoft.IdentityModel.Clients.ActiveDirectory.DLL
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms
    어셈블리 버전: 2.29.0.1078
    Win32 버전: 2.29.40822.1520
    코드베이스: file:///D:/XrmToolbox/Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    어셈블리 버전: 3.0.4.0
    Win32 버전: 3.0.4.0
    코드베이스: file:///D:/XrmToolbox/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2015
    어셈블리 버전: 3.0.4.0
    Win32 버전: 3.0.4.0
    코드베이스: file:///D:/XrmToolbox/WeifenLuo.WinFormsUI.Docking.ThemeVS2015.DLL
----------------------------------------
System.Configuration
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0 built by: NET471REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2612.0 built by: NET471REL1LAST_B
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    어셈블리 버전: 1.0.0.0
    Win32 버전: 4.7.2612.0 built by: NET471REL1LAST_B
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
McTools.StopAdvertisement
    어셈블리 버전: 1.0.0.0
    Win32 버전: 1.0.0.0
    코드베이스: file:///D:/XrmToolbox/McTools.StopAdvertisement.DLL
----------------------------------------
System.Xml.Linq
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0 built by: NET471REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Microsoft.GeneratedCode
    어셈블리 버전: 1.0.0.0
    Win32 버전: 4.7.2612.0 built by: NET471REL1LAST_B
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ComponentModel.Composition
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
Cinteros.Xrm.CRMWinForm
    어셈블리 버전: 2017.9.4.18
    Win32 버전: 2017.9.04.18
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.CRMWINFORM.DLL
----------------------------------------
Cinteros.Xrm.FetchXmlBuilder
    어셈블리 버전: 1.2017.10.3
    Win32 버전: 1.2017.10.003
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.FETCHXMLBUILDER.DLL
----------------------------------------
Cinteros.Xrm.XmlEditorUtils
    어셈블리 버전: 1.2016.4.106
    Win32 버전: 1.2016.4.106
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/CINTEROS.XRM.XMLEDITORUTILS.DLL
----------------------------------------
Cinteros.XTB.ViewDesigner
    어셈블리 버전: 1.2016.8.7
    Win32 버전: 1.2016.8.7
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/CINTEROS.XTB.VIEWDESIGNER.DLL
----------------------------------------
DamSim.SolutionTransferTool
    어셈블리 버전: 1.2018.3.5
    Win32 버전: 1.2018.3.5
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DAMSIM.SOLUTIONTRANSFERTOOL.DLL
----------------------------------------
DamSim.ViewTransferTool
    어셈블리 버전: 1.2018.3.3
    Win32 버전: 1.2018.3.3
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DAMSIM.VIEWTRANSFERTOOL.DLL
----------------------------------------
Develop1.XrmTBPlugin.RibbonWorkbench2016
    어셈블리 버전: 3.1.177.1
    Win32 버전: 3.1.177.1
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DEVELOP1.XRMTBPLUGIN.RIBBONWORKBENCH2016.DLL
----------------------------------------
ITLecChartGuy.AdvancedChartEditor
    어셈블리 버전: 1.2017.8.29
    Win32 버전: 1.2017.8.29
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/ITLECCHARTGUY.ADVANCEDCHARTEDITOR.DLL
----------------------------------------
Javista.XrmToolBox.ImportNN
    어셈블리 버전: 1.2018.3.8
    Win32 버전: 1.2018.3.8
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/JAVISTA.XRMTOOLBOX.IMPORTNN.DLL
----------------------------------------
MsCrmTools.AccessChecker
    어셈블리 버전: 1.2018.7.2
    Win32 버전: 1.2018.7.2
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ACCESSCHECKER.DLL
----------------------------------------
MsCrmTools.AssemblyRecoveryTool
    어셈블리 버전: 1.2018.3.2
    Win32 버전: 1.2018.3.2
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ASSEMBLYRECOVERYTOOL.DLL
----------------------------------------
MsCrmTools.AttributeBulkUpdater
    어셈블리 버전: 1.2016.11.1
    Win32 버전: 1.2016.11.1
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEBULKUPDATER.DLL
----------------------------------------
MscrmTools.AttributeUsageInspector
    어셈블리 버전: 1.2018.7.10
    Win32 버전: 1.2018.7.10
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEUSAGEINSPECTOR.DLL
----------------------------------------
MsCrmTools.AuditCenter
    어셈블리 버전: 1.2016.9.1
    Win32 버전: 1.2016.9.1
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.AUDITCENTER.DLL
----------------------------------------
MsCrmTools.ChartManager
    어셈블리 버전: 1.2017.3.1
    Win32 버전: 1.2017.3.1
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.CHARTMANAGER.DLL
----------------------------------------
MscrmTools.CrmTraceReader
    어셈블리 버전: 1.2018.4.1
    Win32 버전: 1.2018.4.1
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.CRMTRACEREADER.DLL
----------------------------------------
MsCrmTools.DocumentTemplatesMover
    어셈블리 버전: 1.2018.4.3
    Win32 버전: 1.2018.4.3
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.DOCUMENTTEMPLATESMOVER.DLL
----------------------------------------
MsCrmTools.FetchXmlTester
    어셈블리 버전: 1.2017.1123.296
    Win32 버전: 1.2017.1123.296
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FETCHXMLTESTER.DLL
----------------------------------------
MsCrmTools.FlsBulkUpdater
    어셈블리 버전: 1.2016.12.1
    Win32 버전: 1.2016.12.1
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FLSBULKUPDATER.DLL
----------------------------------------
MsCrmTools.FormRelated
    어셈블리 버전: 1.2017.12.3
    Win32 버전: 1.2017.12.3
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FORMRELATED.DLL
----------------------------------------
MsCrmTools.Iconator
    어셈블리 버전: 1.2018.7.9
    Win32 버전: 1.2018.7.9
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ICONATOR.DLL
----------------------------------------
MscrmTools.ManagedSolutionDeletionTool
    어셈블리 버전: 1.2016.11.1
    Win32 버전: 1.2016.11.1
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.MANAGEDSOLUTIONDELETIONTOOL.DLL
----------------------------------------
MsCrmTools.MetadataBrowser
    어셈블리 버전: 1.2018.3.7
    Win32 버전: 1.2018.3.7
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATABROWSER.DLL
----------------------------------------
MsCrmTools.MetadataDocumentGenerator
    어셈블리 버전: 1.2017.1123.296
    Win32 버전: 1.2017.1123.296
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATADOCUMENTGENERATOR.DLL
----------------------------------------
MscrmTools.PortalCodeEditor
    어셈블리 버전: 1.2018.6.8
    Win32 버전: 1.2018.6.8
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.PORTALCODEEDITOR.DLL
----------------------------------------
MscrmTools.PortalRecordsMover
    어셈블리 버전: 1.2018.6.5
    Win32 버전: 1.2018.6.5
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.PORTALRECORDSMOVER.DLL
----------------------------------------
MsCrmTools.SampleTool
    어셈블리 버전: 1.2018.6.23
    Win32 버전: 1.2018.6.23
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SAMPLETOOL.DLL
----------------------------------------
MsCrmTools.ScriptsFinder
    어셈블리 버전: 1.2017.12.6
    Win32 버전: 1.2017.12.6
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SCRIPTSFINDER.DLL
----------------------------------------
MsCrmTools.SecurityRelated
    어셈블리 버전: 1.2018.1.2
    Win32 버전: 1.2018.1.2
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SECURITYRELATED.DLL
----------------------------------------
MsCrmTools.SiteMapEditor
    어셈블리 버전: 1.2018.7.11
    Win32 버전: 1.2018.7.11
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SITEMAPEDITOR.DLL
----------------------------------------
MsCrmTools.SolutionComponentsMover
    어셈블리 버전: 1.2016.6.3
    Win32 버전: 1.2016.6.3
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONCOMPONENTSMOVER.DLL
----------------------------------------
MsCrmTools.SolutionImport
    어셈블리 버전: 1.2017.1123.296
    Win32 버전: 1.2017.1123.296
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONIMPORT.DLL
----------------------------------------
MscrmTools.SyncFilterManager
    어셈블리 버전: 1.2017.3.1
    Win32 버전: 1.2017.3.1
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCFILTERMANAGER.DLL
----------------------------------------
MsCrmTools.SynchronousEventOrderEditor
    어셈블리 버전: 1.2017.1123.296
    Win32 버전: 1.2017.1123.296
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCHRONOUSEVENTORDEREDITOR.DLL
----------------------------------------
MsCrmTools.Translator
    어셈블리 버전: 1.2018.4.6
    Win32 버전: 1.2018.4.6
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.TRANSLATOR.DLL
----------------------------------------
MsCrmTools.UserSettingsUtility
    어셈블리 버전: 1.2018.7.8
    Win32 버전: 1.2018.7.8
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.USERSETTINGSUTILITY.DLL
----------------------------------------
MsCrmTools.ViewLayoutReplicator
    어셈블리 버전: 1.2017.4.4
    Win32 버전: 1.2017.4.4
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.VIEWLAYOUTREPLICATOR.DLL
----------------------------------------
MscrmTools.WebresourcesManager
    어셈블리 버전: 2.2018.7.4
    Win32 버전: 2.2018.7.4
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.WEBRESOURCESMANAGER.DLL
----------------------------------------
MsDyn.Contrib.CloneFieldDefinitions
    어셈블리 버전: 1.1.1.0
    Win32 버전: 1.1.1
    코드베이스: file:///C:/USERS/SERA/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSDYN.CONTRIB.CLONEFIELDDEFINITIONS.DLL
----------------------------------------
System.Net.Http
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0 built by: NET471REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Web
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2633.0 built by: NET471REL1LAST_C
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Design
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0 built by: NET471REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
System.Runtime.Serialization
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2612.0 built by: NET471REL1LAST_B
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
MetadataViewProxies_1b8a5016-0476-4c8a-bd7f-b47389e53faf
    어셈블리 버전: 0.0.0.0
    Win32 버전: 4.7.2556.0
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
System.Windows.Forms.resources
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0 built by: NET471REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ko_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
SMDiagnostics
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2612.0 built by: NET471REL1LAST_B
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2612.0 built by: NET471REL1LAST_B
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
mscorlib.resources
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0 built by: NET471REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ko_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.ServiceModel
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2612.0 built by: NET471REL1LAST_B
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.Data
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2633.0 built by: NET471REL1LAST_C
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Web.Services
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0 built by: NET471REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Web.Services/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.Services.dll
----------------------------------------
Microsoft.VisualBasic
    어셈블리 버전: 10.0.0.0
    Win32 버전: 14.7.2556.0 built by: NET471REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Deployment
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0 built by: NET471REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Deployment/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Deployment.dll
----------------------------------------
System.Deployment.resources
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0 built by: NET471REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Deployment.resources/v4.0_4.0.0.0_ko_b03f5f7f11d50a3a/System.Deployment.resources.dll
----------------------------------------
Microsoft.VisualStudio.Diagnostics.ServiceModelSink
    어셈블리 버전: 4.0.0.0
    Win32 버전: 14.0.23107.0
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualStudio.Diagnostics.ServiceModelSink/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Diagnostics.ServiceModelSink.dll
----------------------------------------
System.Xaml
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2633.0 built by: NET471REL1LAST_C
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
System.ServiceModel.resources
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0 built by: NET471REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.resources/v4.0_4.0.0.0_ko_b77a5c561934e089/System.ServiceModel.resources.dll
----------------------------------------
System.xml.resources
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0 built by: NET471REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.resources/v4.0_4.0.0.0_ko_b77a5c561934e089/System.Xml.resources.dll
----------------------------------------
System.ServiceModel.Channels
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2612.0 built by: NET471REL1LAST_B
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Channels/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Channels.dll
----------------------------------------
System.IdentityModel
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2612.0 built by: NET471REL1LAST_B
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.dll
----------------------------------------
System.IdentityModel.Selectors
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0 built by: NET471REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel.Selectors/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.Selectors.dll
----------------------------------------
System.Security
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0 built by: NET471REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
System.RunTime.Serialization.resources
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0 built by: NET471REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization.resources/v4.0_4.0.0.0_ko_b77a5c561934e089/System.Runtime.Serialization.resources.dll
----------------------------------------
System.IdentityModel.resources
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0 built by: NET471REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel.resources/v4.0_4.0.0.0_ko_b77a5c561934e089/System.IdentityModel.resources.dll
----------------------------------------
System.resources
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0 built by: NET471REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_ko_b77a5c561934e089/System.resources.dll
----------------------------------------
Accessibility
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0 built by: NET471REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT 디버깅 **************
JIT(Just In Time) 디버깅을 사용하려면 이 응용 프로그램 또는 컴퓨터의
config 파일(machine.config)의 jitDebugging 값을 
system.windows.forms 섹션에 설정해야 합니다.
또한 응용 프로그램은 디버깅할 수 있도록 컴파일되어야
합니다.

예:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

JIT 디버깅을 사용하면 처리되지 않은 모든 예외는
이 대화 상자에서 처리되지 않고 컴퓨터에 등록된 JIT 
디버거에 보내집니다.`

**Comment by MscrmTools** [comment]
@sera0731 the error is pretty straight forward : Authentication failed, so something is wrong with your credentials
