### ISSUE TITLE
Solution Transfer Tool:  Timeout Error

### ISSUE THREAD

**Issue by jcirujales** [MscrmTools/XrmToolBox#369]
I'm trying to transfer a solution from CRM on one server to another using the Solution Transfer Tool in the XrmToolBox, but I get an error saying, 

An error occurred:  The request channel timed out while waiting for a reply after 00:01:59:9909880.  Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding.  The time allotted to this operation may have been a portion of a longer timeout.

I've selected a source and target server and choose "Overwrite Unmanaged Customizations," "Publish solution after having imported it," and "Activate plugins steps and workflows," leaving the rest of the options unchecked.  My solutions are rather large (over three hundred entities) but in this case, the solution only contains about ten entities, can someone walk me through the fixes for this?

**Comment by MscrmTools** [comment]
A timeout parameter is available in connection wizard to avoid this problem

**Comment by c0d3m0nky** [comment]
I'm having the same issue, I set the timeout to 20mins when setting up my connection and I'm still getting the error.

**Comment by MscrmTools** [comment]
Ok I will investigate

**Comment by c0d3m0nky** [comment]
Ok, so the timeout isn't saving right. I went in there, it was set to 2:00, changed it to 20:00 and saved. Went back in still 2:00. Opened up the mscrmtools2011.config and all my connections have the Timeout element as 12000000000, if that's milliseconds that's >4 months lol. Closed the app, changed them all to 120000 (20mins in ms), opened a connection, 2:00 again and that connection is back to 12000000000 in the file.

**Comment by MscrmTools** [comment]
Thank you for these precisions, I will fix the bug

**Comment by MscrmTools** [comment]
I found out that the timeout value was not extracted well from the configuration file but the value is saved as expected.

The saved value was also not used when creating the connection. 

I will fix the issue.

In the meantime, please use the new connection string feature to provide a connection string that embeds a timeout value

**Comment by MscrmTools** [comment]
Fixed for the next release!

**Comment by razvanyork** [comment]
I am still getting this error, with both the latest release and the latest prerelease.  I'm using this connection string:
AuthType=AD;Url=https://my.org/org;Organization="org";Domain=mydomain;Username=myusername;Password=mypasswordhere;Timeout=10:10:10
It seems to revert back to 00:02:00.  It may help if the values were validated since I cannot seem to find documentation on what the Timeout should look like in a connection string...

**Comment by MscrmTools** [comment]
When using connectionstring, only the connectionstring is used, nothing else.
So even if you see value "00:02:00" in the connection wizard it is not used and the Timeout value keep defaulted to 2 minutes, but is not used.

**Comment by khanarshan2000** [comment]
I am also facing similar issue here. I am using PowerShell script and using -targetCrmConnectionUrl "ServiceUri=https://xxx.crm.dynamics.com/XRMServices/2011/Organization.svc; Username=xxx; Password=xxx;Timeout=00:05:00" .Will it use the Timeout or it will just use default 00:02:00 ?

**Comment by WynandE** [comment]
Hi All.

I went in and updated the timeout to 20min, saved and it reverted back to 2min like everyone experienced above. I then deleted the connection and recreated it. On re-create I set the timeout to 20min and it saved the change :)

Hope this helps.
