### ISSUE TITLE
Error for older CRM instances

### ISSUE THREAD

**Issue by jsteffen76** [MscrmTools/XrmToolBox#669]
We are experiencing issues on some of our older CRM instances. We are unable to pull settings for users with the user setting utility. We get the attached error message. This just started with the last update we did to XRM Toolbox.
![error](https://user-images.githubusercontent.com/32177172/30714705-de6ec42a-9ee1-11e7-81db-26ffa4eb7e23.jpg)

**Comment by rajyraman** [comment]
This is fixed in the latest version. Refer https://github.com/MscrmTools/MsCrmTools.UserSettingsUtility/issues/15

Please check if you are on v1.2017.8.6

**Comment by jsteffen76** [comment]
I downloaded the pre-released version since mine isn't seeing any updates past v1.2017.7.18. I still get the same error message on v1.2017.829.277

**Comment by jsteffen76** [comment]
I had to do a complete wipe of all data associated with XRM Toolbox for the new release to work properly.
