### ISSUE TITLE
Facing issues with Updating Xrmtoolbox

### ISSUE THREAD

**Issue by nbhar** [MscrmTools/XrmToolBox#798]
I have XRM tool box and I am getting an error while try to update the XRM toolbox.
Any idea how to fix this error? 
I am not able to update the XRM tool box because of this.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.UnauthorizedAccessException: Access to the path 'McTools.StopAdvertisement.dll' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at XrmToolBox.AutoUpdater.AutoUpdater.AutoUpdater_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3130.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
XrmToolBox.AutoUpdater
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/ProgramData/XrmToolBox/XrmToolBox.AutoUpdater.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2670.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by rappen** [comment]
Looks like you should try resetting your installation:
https://www.xrmtoolbox.com/documentation/for-users/reset-xrmtoolbox-installation/

**Comment by nbhar** [comment]
I tried the above procedure but still the issue is same.Also, I am not able to fetch attributes for some of the entities.However, I am able to access every entities using Metadata browser.

**Comment by rappen** [comment]
Could you explain what you mean with fetching attributes etc? That does not seem at all related to upgrade problems, right?

**Comment by nbhar** [comment]
I am using Fetch XML builder to create fetch xml for some entities.
But when I select an entity and then try to fetch the attributes to frame the query, I get metadata not found for the entity. This is causing me serious problems because I am using Advanced Find to fetch the xml which is not  that handy.

**Comment by rappen** [comment]
If you create an issue under the FetchXML Builder repository with more information and perhaps a screenshot I can try to investigate further! :)
https://github.com/rappen/FetchXMLBuilder/issues

**Comment by MscrmTools** [comment]
What about file McTools.StopAdvertisement.dll ?
It seems locked when you try to upgrade
As mentioned by @rappen, a full reset should fix the problem

**Comment by nbhar** [comment]
I reset it and it did not solve the problem. I still get the same error.
Since the issue did not solve and I reloaded my old files and using it now.
At least, I am able to fetch few entities field details now.

**Comment by gregowens** [comment]
I think I've seen the same in the past. Could you try running XrmToolbox as Administrator then trying the update again?

**Comment by nbhar** [comment]
I do not have admin license in my system so can not follow the procedure.

**Comment by gregowens** [comment]
Sorry my comment wasn't exactly clear. I mean running the utility itself as Administrator (right-click the XrmToolbox shortcut and select "Run as administrator" in Windows:
![image](https://user-images.githubusercontent.com/2728236/45613118-26c57600-ba5d-11e8-883b-8a521ab40c25.png)

**Comment by nbhar** [comment]
Hi Greg, as I said I do not have Administrator privileges in my system so the above option will not work for me.
