### ISSUE TITLE
Unable to authenticate to sovereign clouds with current version of XrmTooBox

### ISSUE THREAD

**Issue by dmosier** [MscrmTools/XrmToolBox#974]
XrmToolBox version 1.2020.4.39 and 1.2020.4.40 are not able to authenticate to Dynamics in GCC or GCC High.  Version 1.202.4.38 is able to authenticate.  I believe a new version of XrmToolBox needs to be released using Microsoft.CrmSdk.XrmTooling.CoreAssembly version 9.1.0.49 or higher to address discovery on sovereign clouds.

---
- Deployment: OnPremise
- DB Version: 9.1.0.9237
- XTB Version: 1.2020.4.38

**Comment by MscrmTools** [comment]
Thank you for reporting this. I must admit I'm not working with GCC environments. 

I will try to push a new version soon

**Comment by MscrmTools** [comment]
@dmosier should be fixed with latest version I just released. Can you validate?

**Comment by dmosier** [comment]
I tested version 41.  It is still not able to authenticate to a GCC High instance.  Below is the error message I receive when attempting to connect from version 41.

[cid:image003.jpg@01D69DB5.684804C0]

**Comment by MscrmTools** [comment]
@dmosier sending screenshot through emails does not work. 

You should try to connect using SDK Login control. If it does not work, then it seems it's an issue on MS side.

**Comment by dmosier** [comment]
I tried using the SDK Login control with XRM Toolbox version .41 and it still fails with the same error.  Below is information which may be of assistance in resolving the issue.

CrmConnectControl.dll

Plugin Registration Tool nuget with fixed ConnectControl is available as v9.1.0.20 in https://www.nuget.org/packages/Microsoft.CrmSdk.XrmTooling.PluginRegistrationTool/
Configuration Manager Tool nuget with fix is v9.1.0.34 in https://www.nuget.org/packages/Microsoft.CrmSdk.XrmTooling.ConfigurationMigration.Wpf/
For XRMToolbox, their devs need to rebuild and release a build with version 9.1.0.49 or above https://www.nuget.org/packages/Microsoft.CrmSdk.XrmTooling.CoreAssembly/

**Comment by MscrmTools** [comment]
Well, XrmToolBox v1.2020.10.41 already uses version 9.1.0.51 of Microsoft.CrmSdk.XrmTooling.CoreAssembly, which is the latest one. 
So if SDK login control does not work (and so PRT and CMT too), then there is nothing I can do on my side

**Comment by dmosier** [comment]
The Microsoft tools were fixed in July.  They successfully connect to sovereign clouds.  XRM Toolbox version 39, 40, and 41 will not connect to a sovereign cloud.  This includes GCC, GCC High, and DoD Cloud in the US as well probably includes Azure Germany and Azure Chine 21Vianet.

**Comment by MscrmTools** [comment]
As I said, XrmToolBox already uses latest version of Microsoft assemblies. And when using SDK login control, there is no custom code, this is only Microsoft code that performs the connection.
Moreover, I have no access to any of those kind of environments so I can't even try to fix anything  since I cannot reproduce

**Comment by MscrmTools** [comment]
@dmosier ok, I missed something when releasing latest version of XrmToolBox

So I just released an update of connection controls. When running XrmToolBox, you should be prompted to update them
![image](https://user-images.githubusercontent.com/10774317/97279830-c4deb980-183b-11eb-9dfe-95342325ca5f.png)

Can you try?

**Comment by dmosier** [comment]
I updated to version 41 and then updated to the 1.2020.10.35 connection control.  The error is the same.  It states I do not have access to any organizations in the Microsoft region, even when I select Don’t Know as the region.

It may related to regional discovery service, which changed earlier their year to the global discovery service.  Have you updated the discovery process?

https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/org-service/discovery-service

**Comment by MscrmTools** [comment]
I don't have to. It's up to MS assembly to handle this

**Comment by silgenfritz** [comment]
I am running into the same issue.  I had the same issue with the configuration migration tool as well in the SDK.   I did find this workaround for that issue by adding a line to the config file for the app.  The example below shows the plugin reg tool, but the same worked for the config migration tool.  Seems to be a MSFT issue

  Open PluginRegistration.exe.config file
  Look for appSettings, if you don' find one then add the below tag after system.diagnostics

`<appSettings>
    <add key="SkipDiscovery" value="True" />
</appSettings>`

This will skip calling the default discovery service and will prompt you to enter your instance URL._**

Hope this helps.

**Comment by MscrmTools** [comment]
Thank you @silgenfritz for the info.
Closing the issue for now
